/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainSystemTest {
    @Test public void appHasAGreeting() {
        MainSystem classUnderTest = new MainSystem();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
