/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

public class MainSystem 
{
    public String getGreeting() 
    {
        return "Hello World!";
    }

    public static void main(String[] args) 
    {
        System.out.println(new MainSystem().getGreeting());
    }
}
